<a href="https://colab.research.google.com/github/LIBY70/-goinhwal/blob/Hw/hw2_22012167_%EB%85%B8%EC%A3%BC%ED%98%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

문제 1.

1~10 정수에서 랜덤하게 뽑아 구성한 3 by 4 matrix를 만들고, 각 열 별로 평균
(μ)과 표준편차(σ)를 구한 뒤, 각 열 별로 해당 μ - σ 보다 큰 element의 개수를 구하시오.

In [56]:
import numpy as np

#1~10 사이의 정수로 구성된 3x4 행렬 생성
data = np.random.randint(1, 11, size=(3, 4))
data

array([[ 1,  5,  4,  5],
       [ 6,  5, 10,  3],
       [ 2,  8,  8,  7]])

In [57]:
#평균
mean = np.mean(data, axis=0)
mean

array([3.        , 6.        , 7.33333333, 5.        ])

In [58]:
##표준편차
std = np.std(data, axis=0)
std

array([2.1602469 , 1.41421356, 2.49443826, 1.63299316])

In [59]:
#평균 - 표준편차 값보다 큰 요소의 개수
count = data > (mean - std)
count = np.sum(count, axis = 0)
count

array([3, 3, 2, 2])

문제 2. pandas_data1.txt를 읽어서 다음을 출력하시오 (‘이름’을 index로 선택).
1) 이여섯, 최아홉 학생의 기말점수 (DataFrame 형태로)
2) 마지막 6명 학생의 출석, 과제 점수4
과제물 2.

In [69]:
import pandas as pd

df = pd.read_csv('pandas_data1.txt', sep='\t', index_col='이름', encoding='euc-kr')
df

      성별   학년    중간  기말  출석   과제
이름
김둘    여자  1.0   NaN  36   5   75
김셋    남자  2.0  17.0  20   5   96
김여섯   남자  2.0  28.0  20   4   83
김일곱   남자  NaN  20.0  44   6   82
김여덜  NaN  1.0  20.0  24   8   88
김아홉   남자  3.0  23.0  45  10   92
김열    남자  3.0  16.0  47   5   83
이다섯   남자  3.0  21.0  35   5   92
이아홉   남자  3.0  20.0  36   5   87
이열    여자  4.0  28.0  41   9   87
박하나   남자  4.0  30.0  25   7   86
박둘    남자  4.0  20.0  31   7   76
박여섯   여자  1.0  24.0  37   7   91
김하나   여자  2.0  19.0  18   8   88
박열    남자  3.0  23.0  20   6   80
최하나   여자  1.0  29.0  39   5   83
최둘    남자  1.0  18.0  29   5   86
최셋    남자  2.0  29.0  39   7   84
이여섯   여자  3.0  22.0  38   7   78
이일곱   남자  3.0  24.0  32   8   87
이여덜   여자  4.0  17.0  47   5   70
최여덜   남자  4.0  13.0  48   8   89
최아홉   남자  1.0  21.0  33   3  100
최열    여자  2.0  16.0  50  10  100
김넷    남자  1.0  18.0  28   7   93
김다섯   남자  2.0  24.0  18   6   84
이하나   남자  3.0  29.0  17   5   79
이둘    남자  4.0  30.0  42   8   98
이셋    남자  4.0  22.0  50   4   79
이넷    여자  4.0  24.0  21  10   89

In [74]:
df1 = df.loc[['이여섯','최아홉'], ['기말']]
df1

     기말
이름
이여섯  38
최아홉  33

In [82]:
df2 = df.loc[-6:, ['출석', '과제']]
df2

TypeError: cannot do slice indexing on Index with these indexers [-6] of type int